services:
  - type: web
    name: stackoverflow-api
    runtime: node
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URL
        sync: false # Set this in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://stackoverflow-yi2x.vercel.app
